name: constrained_scrollable_views
description: Set of useful scrollable views includes ConstrainedScrollView, ScrollableColumn, and ScrollableRow.
version: 1.0.3
homepage: https://github.com/phimary/constrained_scrollable_views

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
